### ISSUE TITLE
broadlink.exceptions.NetworkTimeoutError: [Errno -4000] Network timeout

### ISSUE THREAD

**Issue by kuradi** [algirdasc/hass-floureon#15]
i have this error in my logs. climate sitill working...

`Logger: homeassistant.core
Source: custom_components/floureon/climate.py:218
First occurred: 13:39:40 (2 occurrences)
Last logged: 15:00:45

Error executing service: <ServiceCall climate.set_temperature (c:560810a4769ad53dd070e148978ab6c1): temperature=22.0, hvac_mode=heat, entity_id=['climate.porandakute']>
Error executing service: <ServiceCall climate.set_temperature (c:64bacbd127271c862c505dd445e1f587): temperature=22.0, hvac_mode=heat, entity_id=['climate.porandakute']>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/broadlink/device.py", line 320, in send_packet
    resp, _ = conn.recvfrom(2048)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1504, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1523, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 642, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 681, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 679, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 544, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/floureon/climate.py", line 218, in async_set_temperature
    device.set_mode(BROADLINK_MODE_MANUAL, self._thermostat_loop_mode, self.thermostat_get_sensor())
  File "/usr/local/lib/python3.8/site-packages/broadlink/climate.py", line 117, in set_mode
    self.send_request(bytearray([0x01, 0x06, 0x00, 0x02, mode_byte, sensor]))
  File "/usr/local/lib/python3.8/site-packages/broadlink/climate.py", line 36, in send_request
    response = self.send_packet(0x6a, request_payload)
  File "/usr/local/lib/python3.8/site-packages/broadlink/device.py", line 325, in send_packet
    raise exception(-4000)  # Network timeout.
broadlink.exceptions.NetworkTimeoutError: [Errno -4000] Network timeout
`

**Comment by ChaoticBD** [comment]
have the same issue =c

**Comment by dimitris444** [comment]
Me too...This error originated from a custom integration.

Thermostat 192.168.1.119 set_time error: [Errno -4000] Network timeout

**Comment by kuradi** [comment]
there is something strange going on....
i have long time situation when nodered losing connection to ha websocket... ive been watching logs and nothing... and now...
![image](https://user-images.githubusercontent.com/31483391/159273488-d97ff212-6db6-4007-a8bd-dd26a03058b9.png)
those are errors for climate and on exactly same times i have drops of websocket. 
help?
