### ISSUE TITLE
Integration not working anymore

### ISSUE THREAD

**Issue by parsonsagain** [algirdasc/hass-floureon#23]
Hello,

Any ideas for the following error

This error originated from a custom integration.

Logger: homeassistant.core
Source: custom_components/floureon/__init__.py:44
Integration: floureon (documentation, issues)
First occurred: 16:30:43 (10 occurrences)
Last logged: 16:31:58

Error executing service: <ServiceCall climate.set_hvac_mode (c:681a14a3ca5105dbfd7e13b438f3aa56): entity_id=['climate.heat'], hvac_mode=heat>
Error executing service: <ServiceCall climate.set_hvac_mode (c:51f988c75dc38c33d06c58c984ed9102): entity_id=['climate.heat'], hvac_mode=auto>
Error executing service: <ServiceCall climate.set_hvac_mode (c:6bd87baa851d09e8100e44cb788d069b): entity_id=['climate.heat'], hvac_mode=auto>
Error executing service: <ServiceCall climate.set_hvac_mode (c:3efad71261fa819d039e61287600db2b): entity_id=['climate.heat'], hvac_mode=auto>
Error executing service: <ServiceCall climate.set_hvac_mode (c:835ae0a8c4fd51dd77e4f9a16fd5b694): entity_id=['climate.heat'], hvac_mode=auto>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/broadlink/__init__.py", line 204, in hello
    return next(
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1648, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1667, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 668, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/config/custom_components/floureon/climate.py", line 231, in async_set_hvac_mode
    device = self._thermostat.device()
  File "/config/custom_components/floureon/__init__.py", line 44, in device
    return broadlink.hello(self._host, timeout=3)
  File "/usr/local/lib/python3.9/site-packages/broadlink/__init__.py", line 208, in hello
    raise e.NetworkTimeoutError(
broadlink.exceptions.NetworkTimeoutError: [Errno -4000] Network timeout: No response received within 3s

**Comment by algirdasc** [comment]
Errno -4000 means that thermostat cannot be reached or did not respond propely. If thermostat was working good before - maybe IP has changed or thermostat is unreachable. If you setting up it first time, might be that your thermostat is not broadlink based and is not supported.
