### ISSUE TITLE
NetworkTimeoutError: [Errno -4000] Network timeout: No response received within 3s

### ISSUE THREAD

**Issue by jaimecallejon** [algirdasc/hass-floureon#32]
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/floureon/__init__.py:44
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: December 12, 2022 at 11:39:02 PM (1 occurrences)
Last logged: December 12, 2022 at 11:39:02 PM

[2805808576] [Errno -4000] Network timeout: No response received within 3s
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/broadlink/__init__.py", line 225, in hello
    return next(
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1745, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1782, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/config/custom_components/floureon/climate.py", line 240, in async_set_hvac_mode
    device = self._thermostat.device()
  File "/config/custom_components/floureon/__init__.py", line 44, in device
    return broadlink.hello(self._host, timeout=3)
  File "/usr/local/lib/python3.10/site-packages/broadlink/__init__.py", line 229, in hello
    raise e.NetworkTimeoutError(
broadlink.exceptions.NetworkTimeoutError: [Errno -4000] Network timeout: No response received within 3s

**Comment by edi214** [comment]
HI! i have the same issue:

Logger: custom_components.floureon
Source: custom_components/floureon/__init__.py:70
Integration: floureon ([documentation](https://github.com/algirdasc/hass-floureon), [issues](https://github.com/algirdasc/hass-floureon/issues))
First occurred: 18 марта 2023 г. в 07:18:52 (4 occurrences)
Last logged: 03:13:53

    Thermostat 10.10.9.91 read_status error: [Errno -4000] Network timeout: No response received within 10s
    Thermostat 10.10.9.91 read_status error: [Errno -4000] Network timeout: No response received within 3s

**Comment by Raydo666** [comment]
Hi! Same issue + time update is -3h. I disabled it in climate.py. 
My time zone is Europe/Helsinki 
It always changes to utc
It generally works. 
It's just a bit disturbing when they disappear for a while and reappear at random moments.
Sorry for my bad English.
Greetings

**Comment by moose75** [comment]
Hi, trying to integrate a Beok TGM50 thermostat  ([https://fr.aliexpress.com/item/1005006036416821.html].
Got the same error you reported :
```
2023-11-27 21:56:41.349 ERROR (SyncWorker_0) [custom_components.floureon] Thermostat 192.168.1.80 network error: [Errno -4000] Network timeout: No response received within 3s
2023-11-27 21:56:41.350 WARNING (SyncWorker_0) [custom_components.floureon] Thermostat 192.168.1.80 read_status() error: 'NoneType' object has no attribute 'auth'
2023-11-27 21:57:41.298 ERROR (SyncWorker_2) [custom_components.floureon] Thermostat 192.168.1.80 network error: [Errno -4000] Network timeout: No response received within 3s
2023-11-27 21:57:41.298 WARNING (SyncWorker_2) [custom_components.floureon] Thermostat 192.168.1.80 read_status() error: 'NoneType' object has no attribute 'auth'

```
Any help is welcome, because I'm new to HA, with poor knowledge in Python.
Thanks in advance
- Jean-Claude (Bergerac, France)

**Comment by edi214** [comment]
Hi!
I have no solution of this issue yet...
But in my case it is have another description than you:

Logger: custom_components.floureon
Source: custom_components/floureon/__init__.py:78
Integration: floureon (documentation, issues)
Thermostat 10.10.9.91 read_status() error: [Errno -4000] Network timeout:
No response received within 10s
Thermostat 10.10.9.93 read_status() error: ('hysen_response_error', 'CRC
check on response failed')
Thermostat 10.10.9.92 read_status() error: ('hysen_response_error', 'CRC
check on response failed')

вт, 28 нояб. 2023 г. в 02:21, moose75 ***@***.***>:

**Comment by lucasleal** [comment]
Hi @moose75,

Did you have any progress with the TGM50 ?
Thanks,

Lucas
